name: HomelandSecurity
main: com.pvpMinecraft.HomelandSecurityPlugin
version: '0.0.1'
author: MCShovel
load: POSTWORLD
softdepend: [Vault, WorldEdit, WorldGuard, Movecraft, Cannons]

commands:
   claim:
      description: Claim land for your use and keep the bad guys out.
      usage: /claim
      permission: homeland.player
      permission-message: 'ยง4You do not have permission to perform this action.'
